services:
  - type: web
    name: finergize-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: USE_OPENAI
        value: true
      - key: MODEL_PATH
        value: models/finergize_recommender_agent.joblib
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.10.11